export const requestsList = [
	{
		id: 'EIR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "Urgent Processing",
		reason: "",
		collection: 'requests',
		serviceType: 'EIR / COP',
	},
	{
		id: 'PMR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "Need by tomorrow",
		reason: "",
		collection: 'requests',
		serviceType: 'Priority Movement',
	},
	{
		id: 'WSR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Accepted',
		documents: ['dummy.pdf'],
		remarks: "Urgent Processing",
		reason: "Verified Documents",
		collection: 'requests',
		serviceType: 'Weightment Slip',
	},
	{
		id: 'WSR-002',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Rejected',
		documents: ['dummy.pdf'],
		remarks: "Requested change",
		reason: "Missing documents",
		collection: 'requests',
		serviceType: 'Weightment Slip',
	},
	{
		id: 'SER-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Accepted',
		documents: ['dummy.pdf'],
		remarks: "Requested by Consingnee",
		reason: "Verified Documents",
		collection: 'requests',
		serviceType: 'Special Equipments',
	},
	{
		id: 'SER-002',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Rejected',
		documents: ['dummy.pdf'],
		remarks: "Requested by Consingnee",
		reason: "Not available right now",
		collection: 'requests',
		serviceType: 'Special Equipments',
	},
	{
		id: 'CGR-002',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Accepted',
		documents: ['dummy.pdf'],
		remarks: "Requested by Consingnee",
		reason: "Verified",
		collection: 'requests',
		serviceType: 'Container Grounding',
	},
	{
		id: 'CSR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Accepted',
		documents: ['dummy.pdf'],
		remarks: "Urgent Processing",
		reason: "Verified Documents",
		collection: 'requests',
		serviceType: 'Container Staging',
	},
	{
		id: 'RSR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "Unequal Weight from start",
		reason: "",
		collection: 'requests',
		serviceType: 'Re-Scanning',
	},
	{
		id: 'CAR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "",
		reason: "",
		collection: 'requests',
		serviceType: 'Cheque Acceptance',
	},
	{
		id: 'TIR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "",
		reason: "",
		collection: 'requests',
		serviceType: 'Tax Invoice',
	},
	{
		id: 'JUR-001',
		order: {
			id: 'ORD-001',
			cfs: {
				id: 'chennai-cfs',
				title: "Chennai Port CFS",
				location: "Chennai Port, Tamil Nadu",
			},
		},
		date: '10 January 2024',
		status: 'Pending',
		documents: ['dummy.pdf'],
		remarks: "Urgent Processing",
		reason: "",
		collection: 'requests',
		serviceType: 'Job Order Update',
	},
];
